<?php // $Id$

/**
 * @file
 * The Migration module, which helps keep databases in sync.
 *
 * The Migration module is intended to help keep development, staging and
 * production databases in sync. This is done by collecting queries and
 * formatting them as a hook_update_N functon for running on the target
 * site.
 */

/**
 * Implementation of hook_menu().
 */
function migration_menu() {
  $items = array();

  $items['admin/settings/migration'] = array(
    'title' => 'Migration',
    'description' => 'Settings for the Migration module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('migration_settings_form'),
    'access arguments' => array('administer migration'),
  );

  return $items;
}

/**
 * Admin settings form.
 */
function migration_settings_form($form_state) {
  $form = array();

  $form['migration_module_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Module name'),
    '#description' => t('Enter the module name used in the hook_update_N call.'),
    '#default_value' => variable_get('migration_module_name', migration_id_safe(variable_get('site_name', 'Drupal'))),
  );

  return system_settings_form($form);
}

function migration_id_safe($string) {
  $search = array(' ', '-');
  return strtolower(str_replace($search, '', $string));
}

/**
 * Implementation of hook_exit().
 *
 * Migration saves all the queries that occurred during this page view.
 */
function migration_exit($destination = NULL) {

  $page_queries = migration_global_queries_processor();
  $valid_queries = migration_filterqueries($page_queries);

  foreach ($valid_queries as $querystruct) {
    $functions[$querystruct['function']] = $querystruct['function'];
    $usernames[$querystruct['username']] = $querystruct['username'];
    $querystrings[$querystruct['querystring']] = $querystruct['querystring'];
    $tablename = migration_get_tablename($querystruct['querystring']);
    $tablenames[$tablename] = $tablename;

    // TODO: for debugging - get rid of this later
    // $funcquery[$querystruct['function'] . $querystruct['querystring']] = $querystruct['function'] . $querystruct['querystring'];
  }

  // Log the sql strings to disk.
  if (TRUE) {

    if (migration_file_append_data(implode("\n", $querystrings), 'queries.sql')) {
      $output .= t('Migration file saved at !file', array('!file' => realpath($migration_get_filename)));
    }
    else {
      $output .= t('Error saving sql file.');
    }

    if (TRUE) {
      $output .= migration_format_update_hook($queries);
    }
  }
  print $output;
}

function migration_get_filename($file) {
  // TODO: Should be a configurable option that comes from the database.
  $filename = file_directory_path() . '/' . $file;
  return $filename;
}

/**
 * Takes the global queries and extracts the query strings, the username, and the function called.
 *
 * @return
 *   An array containing the query data.
 */
function migration_global_queries_processor() {
  global $queries;
  foreach ($queries as $query){
    //regex explain: using % instead of /, the 's' extends the match past single lines.
    preg_match("%(?<function>.*)\n\/\* (?<username>.*) : .*\*\/ (?<querystring>.*)%s", $query[0], $matchedquery);
    //strip initial space
    $matchedquery['querystring'] = preg_replace("/^ */s", "", $matchedquery['querystring']);
    //strip linefeeds
    $matchedquery['querystring'] = preg_replace("/\n/s", "", $matchedquery['querystring']);
    
    $splitqueries[] = $matchedquery;
  }

  return $splitqueries;
}

function migration_file_append_data($input, $filename) {
  // TODO: Fix to get this from the database.
  $file = file_directory_path() . '/' . $filename;
  $file = realpath($file);
  $data = file_get_contents($file);
  $data .= $input;
  $return = file_save_data($data, $file, FILE_EXISTS_REPLACE);

  return $return;
}

function migration_query_row($sql) {
  $output .= "  $sql = array($sql);\n";
  return $output;
}

/**
 * This function strips out the individual querystructs that we dont want to
 * keep.
 */
function migration_filterqueries($querystruct) {
  // Filter by querystring
  foreach ($querystruct as $query) {
    if (!migration_is_select($query['querystring'])) {
      // its *not* a select, so it will change the database.
      // next lets find out if we care if it changes the db.

      // First we check our configured table name list.
      // If its in the "do not record list" we ditch it.
      $tablename = migration_get_tablename($query['querystring']);
      if (migration_is_table_to_record($tablename)) {
      // Secondly we check the configured function list
      // we will delete by function if we know there are functions we dont care about
      // Finally, if we want to filter by username we can.. later.. later..
        $filteredstruct[] = $query;
      }
    }
  }
  return $filteredstruct;
}
 
function migration_get_tablename($sqlstring){

  preg_match("/(INSERT INTO|DELETE FROM|ALTER TABLE|UPDATE|DROP VIEW|CREATE VIEW|DROP TABLE|CREATE TABLE|LOCK TABLES|CREATE DOMAIN|CREATE INDEX|CREATE UNIQUE INDEX|CREATE SEQUENCE|DROP INDEX) (?<tablename>.*?)($| ).*/", $sqlstring, $splitqueries[]);
  return $splitqueries[0]['tablename'];
}

function migration_is_table_to_record($tablename) {
  // TODO: Record them all for now. Get table name list from the database.
  // Do we store the good tables or the bad ones?
  // Record the bad ones.  This will eventually be configurable in the
  // interface much like backup/migrate.  
  $skiptables = array(
    'cache_views',
    'cache',
    'cache_content',
    'cache_menu',
    'cache_admin_menu',
    'cache_update',
    'cache_block',
    'cache_filter',
    'cache_page',
    'history',
    'menu_router',
    'menu_links',
    'watchdogcache',
    'watchdog',
    'cache_calendar_ical',
    'cache_form',
    'sessions',
    'search_dataset',
    'search_index',
    'search_keywords_log',
    'search_total',
    'accesslog',
    'devel_queries',
    'devel_times',
    'menu_router',
    'menu_links',

  );

  if (in_array($tablename, $skiptables)) {
    // TODO: Debug
    // print_r ("<H1>irrelevant table $tablename<BR></H1>");
    return FALSE;
  }
  return TRUE;
}

function migration_is_select($sqlstring) {
  $process = FALSE;
  // Filter out all the queries beginning with SELECT.
  // Note that we dont want to skip *all* queries that contain SELECT.
  // Just the ones that start with SELECT (sub-selects are fine).
  if (stripos($sqlstring, 'SELECT') === 0) {
    $process = TRUE;
  }
  return $process;
}

function migration_keepquery($query) {
  // TODO: Either make this configurable or ensure we're excluding the right stuff.

  $process = TRUE;
  $query = trim($query);

  // Starts with...
  if (stripos($query, 'SELECT') === 0 ||
      stripos($query, 'DELETE') === 0 ||
      stripos($query, 'INSERT INTO cache') === 0 ||
      stripos($query, 'INSERT INTO search_') === 0 ||
      stripos($query, 'INSERT INTO watchdog') === 0 ||
      stripos($query, 'INSERT INTO system') === 0 ||
      stripos($query, 'INSERT INTO menu_router') === 0 ||
      stripos($query, 'UPDATE cache') === 0 ||
      stripos($query, 'UPDATE history') === 0 ||
      stripos($query, 'SHOW TABLES') === 0 ||
      stripos($query, 'UPDATE system') === 0 ||
      stripos($query, 'UPDATE sessions') === 0 ||
      stripos($query, 'UPDATE users SET access =') === 0 ||
      stripos($query, 'UPDATE search_total') === 0 ||
      stripos($query, 'UPDATE menu_link') === 0) {
    $process = FALSE;
  }

  // Starts with...
  if (stripos($query, 'UPDATE variable') === 0) {
    // Contains...
    if (stripos($query, 'update_last_check') === TRUE ||
        stripos($query, 'poormanscron_lastrun') === TRUE ||
        stripos($query, 'node_cron_comments_scale') === TRUE ||
        stripos($query, 'node_cron_views_scale') === TRUE ||
        stripos($query, 'node_cron_last') === TRUE ||
        stripos($query, 'cron_last') === TRUE) {
      $process = FALSE;
    }
  }

  return $process;
}

function migration_format_update_hook($queries) {
  global $queries;
  $count = migration_get_next_id();

  $output = '<code><pre>';
  $output .= "function mymodule_update_$count() {\n";
  $output .= '  $sql = array();';

  foreach ($queries as $data) {
    $bits = explode("\n", $data[0]);
    $query = preg_replace('|\/\*\s[a-z\s:_]*\*\/\s|', '', $bits[1]);

    $process = migration_keepquery($query);
    if ($process) {
      $output .= "\n";
      $output .= "  /* $bits[0] */\n";
      $output .= '  $sql[] = update_sql($query);';
    }

  }
  $output .= "\n  return \$sql;\n}\n";
  $output .= '</pre></code>';

  return $output;
}

function migration_get_next_id() {
  // TODO: Retrieve next update N from system table.
  return 6000;
}
